# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js LTS on Alpine for building
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts

# Copy all source files and build
COPY . .
RUN npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=builder /app/dist ./dist
COPY package.json ./
RUN npm install --production --ignore-scripts

# Run the MCP server over stdio
ENTRYPOINT ["node", "dist/index.js"]
